android.enableJetifier=true
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.vfs.watch=true
# AAPT2 override handled via build-tools wrapper
